version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      #Volume dos dados
      - dados:/var/lib/postgresql/data
      #Scripts
      - C:/Users/vinic/docker/email/scripts:/scripts
      - C:/Users/vinic/docker/email/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      #site
      - C:/Users/vinic/docker/email/web:/usr/share/nginx/html/
      #configuração proxy reverso
      - C:/Users/vinic/docker/email/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      #aplicacao
      - C:/Users/vinic/docker/email/app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=email_sender
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      #worker
      - C:/Users/vinic/docker/email/worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue